require "rake"
require "fileutils"
require "ffi"

libbigwig_dir = File.expand_path("libBigWig", __dir__)
target_dir = "../../vendor"
target_fname = FFI.map_library_name("libBigWig")
target_path = File.join(target_dir, target_fname)

task default: ["libbigwig:build", "libbigwig:clean"]

namespace :libbigwig do
  desc "Build the libbigwig library"
  task :build do
    Dir.chdir(libbigwig_dir) do
      sh "make"
      FileUtils.mkdir_p(target_dir) # Windows
      warn "mkdir -p #{target_dir}"
      sh "cp #{target_fname} #{target_path}"
    end
  end

  task cleanall: [:clean]

  desc "Clean the libbigwig library"
  task :clean do
    Dir.chdir(libbigwig_dir) do
      sh "make clean"
    end
  end

  desc "Clean all"
  task :cleanall do
    Dir.chdir(libbigwig_dir) do
      sh "rm #{target_path}" if File.exist?(target_path)
    end
  end
end
