
name: test
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
      fail-fast: false
        os:   [ 'ubuntu', 'macos' ]
        ruby: [ '3.1', '3.2', '3.3' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install libcurl4 (ubuntu)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          sudo apt install libcurl4-openssl-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake compile
      - run: bundle exec rake test
